project_id                   = "rxo-service"
network_project_id           = "rxo-dev"
region                       = "us-central1"
zone                         = "us-central1-a"
network_name                 = "rxo-vpc"
database_version             = "POSTGRES_9_6"
tier                         =  "db-custom-1-3840"